extract_json_prompt = """
You are an expert data extractor and transformer. Your task is to analyze the raw questionnaire data provided below and convert it into a structured JSON array. The final JSON MUST conform to the provided schema.

RULES FOR EXTRACTION:
1. Identify and extract data from the columns: '#', 'Section', 'Question', and 'Answer'.
2. The 'title' should be extracted from the main header of the questionnaire (e.g., "SURVEY QUESTIONS" or a derived, clear title like "Project Requirements Questionnaire").
3. **Handle Missing Sections:** If the 'Section' column is blank for a row, you must use the value from the nearest preceding non-blank 'Section' (apply forward-fill logic).
4. Ignore the numeric index column generated by Pandas (if present) in the final JSON extraction.

RAW QUESTIONNAIRE DATA (Pandas DataFrame String):
---
{questionaire_text} 
---
"""

